// Table examples for the auxiliary/table endpoint
// Structure mirrors chart examples metadata and embeds a table payload

const tableExamples = [
  {
    id: "demand-fulfillment-table",
    headline: "Demand vs Fulfillment by Region",
    timestamp: "2024-12-01T15:00:00Z",
    preamble: "Operational snapshot of demand priority vs fulfilled units",
    content:
      "This table highlights regional demand, allocation shortfalls, and fulfillment status for priority SKUs.",
    table: {
      rowIdentifier: "id",
      headers: [
        { text: "Demand Priority", accessorKey: "demandPriority" },
        { text: "Product Family", accessorKey: "productFamily" },
        { text: "System", accessorKey: "system" },
        { text: "Region", accessorKey: "region" },
        { text: "Created Date", accessorKey: "created_date" },
        { text: "Demand Units", accessorKey: "demandUnits" },
        { text: "Fulfilled Demand Units", accessorKey: "fulfilledDemandUnits" },
      ],
      rows: [
        {
          id: "1",
          demandPriority: 1,
          productFamily: "HGS",
          system: "H100",
          region: "North America",
          created_date: "2024-03-15",
          demandUnits: "100K",
          fulfilledDemandUnits: "80k",
        },
        {
          id: "2",
          demandPriority: 2,
          productFamily: "DGI",
          system: "B110",
          region: "Asia",
          created_date: "2024-01-22",
          demandUnits: "100K",
          fulfilledDemandUnits: "80k",
        },
        {
          id: "3",
          demandPriority: 3,
          productFamily: "HGD",
          system: "System",
          region: "Europe",
          created_date: "2024-05-08",
          demandUnits: "100K",
          fulfilledDemandUnits: "80k",
        },
        {
          id: "4",
          demandPriority: 4,
          productFamily: "DGE",
          system: "B100",
          region: "South America",
          created_date: "2024-02-14",
          demandUnits: "100K",
          fulfilledDemandUnits: "80k",
        },
        {
          id: "5",
          demandPriority: 5,
          productFamily: "HGC",
          system: "B110",
          region: "Africa",
          created_date: "2024-06-30",
          demandUnits: "100K",
          fulfilledDemandUnits: "80k",
        },
        {
          id: "6",
          demandPriority: 6,
          productFamily: "DGT",
          system: "System",
          region: "Pacific",
          created_date: "2024-04-12",
          demandUnits: "100K",
          fulfilledDemandUnits: "80k",
        },
        {
          id: "7",
          demandPriority: 7,
          productFamily: "HGP",
          system: "B110",
          region: "North America",
          created_date: "2024-07-19",
          demandUnits: "100K",
          fulfilledDemandUnits: "80k",
        },
        {
          id: "8",
          demandPriority: 8,
          productFamily: "DGS",
          system: "H100",
          region: "Asia",
          created_date: "2024-03-05",
          demandUnits: "100K",
          fulfilledDemandUnits: "80k",
        },
        {
          id: "9",
          demandPriority: 9,
          productFamily: "HGI",
          system: "H200",
          region: "Europe",
          created_date: "2024-08-01",
          demandUnits: "100K",
          fulfilledDemandUnits: "80k",
        },
        {
          id: "10",
          demandPriority: 10,
          productFamily: "DGS",
          system: "System",
          region: "South America",
          created_date: "2024-01-10",
          demandUnits: "100K",
          fulfilledDemandUnits: "80k",
        },
        {
          id: "11",
          demandPriority: 11,
          productFamily: "HGI",
          system: "B100",
          region: "Africa",
          created_date: "2024-05-20",
          demandUnits: "100K",
          fulfilledDemandUnits: "80k",
        },
        {
          id: "12",
          demandPriority: 12,
          productFamily: "DGD",
          system: "H200",
          region: "Pacific",
          created_date: "2024-02-28",
          demandUnits: "100K",
          fulfilledDemandUnits: "80k",
        },
        {
          id: "13",
          demandPriority: 13,
          productFamily: "HGE",
          system: "System",
          region: "North America",
          created_date: "2024-06-07",
          demandUnits: "100K",
          fulfilledDemandUnits: "80k",
        },
        {
          id: "14",
          demandPriority: 14,
          productFamily: "DGC",
          system: "B100",
          region: "Asia",
          created_date: "2024-04-03",
          demandUnits: "100K",
          fulfilledDemandUnits: "80k",
        },
        {
          id: "15",
          demandPriority: 15,
          productFamily: "DGC",
          system: "B100",
          region: "Europe",
          created_date: "2024-07-25",
          demandUnits: "100K",
          fulfilledDemandUnits: "80k",
        },
        {
          id: "16",
          demandPriority: 16,
          productFamily: "HGE",
          system: "B110",
          region: "South America",
          created_date: "2024-03-18",
          demandUnits: "100K",
          fulfilledDemandUnits: "80k",
        },
        {
          id: "17",
          demandPriority: 17,
          productFamily: "DGD",
          system: "H100",
          region: "Africa",
          created_date: "2024-05-11",
          demandUnits: "100K",
          fulfilledDemandUnits: "80k",
        },
        {
          id: "18",
          demandPriority: 18,
          productFamily: "HGI",
          system: "System",
          region: "Pacific",
          created_date: "2024-01-25",
          demandUnits: "100K",
          fulfilledDemandUnits: "80k",
        },
        {
          id: "19",
          demandPriority: 19,
          productFamily: "DGS",
          system: "B110",
          region: "North America",
          created_date: "2024-06-14",
          demandUnits: "100K",
          fulfilledDemandUnits: "80k",
        },
        {
          id: "20",
          demandPriority: 20,
          productFamily: "HGP",
          system: "H200",
          region: "Asia",
          created_date: "2024-04-29",
          demandUnits: "100K",
          fulfilledDemandUnits: "80k",
        },
      ],
    },
  },
  {
    id: "supplier-backlog-table",
    headline: "Supplier Backlog and Commit Status",
    timestamp: "2024-12-02T10:00:00Z",
    preamble: "Backlog vs committed units by supplier and region",
    content:
      "Use this to identify suppliers with persistent backlogs and low commit reliability.",
    table: {
      rowIdentifier: "id",
      headers: [
        { text: "Supplier", accessorKey: "supplier" },
        { text: "SKU", accessorKey: "sku" },
        { text: "Region", accessorKey: "region" },
        { text: "Created Date", accessorKey: "created_date" },
        { text: "Backlog Units", accessorKey: "backlogUnits" },
        { text: "Committed Units", accessorKey: "committedUnits" },
        { text: "Priority", accessorKey: "priority" },
      ],
      rows: [
        { id: "1", supplier: "Alpha Co", sku: "NV-9001", region: "North America", created_date: "2024-03-10", backlogUnits: 12000, committedUnits: 8000, priority: 1 },
        { id: "2", supplier: "Beta Ltd", sku: "NV-9002", region: "Europe", created_date: "2024-03-12", backlogUnits: 9000, committedUnits: 7000, priority: 2 },
        { id: "3", supplier: "Gamma Inc", sku: "NV-9003", region: "Asia", created_date: "2024-03-15", backlogUnits: 15000, committedUnits: 9000, priority: 1 },
        { id: "4", supplier: "Delta LLC", sku: "NV-9004", region: "Africa", created_date: "2024-03-18", backlogUnits: 4000, committedUnits: 3500, priority: 3 },
        { id: "5", supplier: "Epsilon BV", sku: "NV-9005", region: "South America", created_date: "2024-03-20", backlogUnits: 11000, committedUnits: 9500, priority: 2 },
        { id: "6", supplier: "Zeta GmbH", sku: "NV-9006", region: "Pacific", created_date: "2024-03-22", backlogUnits: 6000, committedUnits: 5000, priority: 3 },
      ],
    },
  },
  {
    id: "inventory-positions-table",
    headline: "Inventory Positions by Location",
    timestamp: "2024-12-03T09:30:00Z",
    preamble: "On-hand, in-transit, and safety stock levels",
    content:
      "Evaluate buffer health and potential stockouts across DCs and plants.",
    table: {
      rowIdentifier: "id",
      headers: [
        { text: "Product", accessorKey: "product" },
        { text: "Location", accessorKey: "location" },
        { text: "Created Date", accessorKey: "created_date" },
        { text: "On Hand", accessorKey: "onHand" },
        { text: "In Transit", accessorKey: "inTransit" },
        { text: "Safety Stock", accessorKey: "safetyStock" },
      ],
      rows: [
        { id: "1", product: "GPU H100", location: "DC-NA-01", created_date: "2024-02-10", onHand: 5200, inTransit: 1200, safetyStock: 3000 },
        { id: "2", product: "GPU H200", location: "DC-EU-02", created_date: "2024-02-12", onHand: 3400, inTransit: 900, safetyStock: 2500 },
        { id: "3", product: "Board B110", location: "PL-AS-01", created_date: "2024-02-15", onHand: 2100, inTransit: 1500, safetyStock: 1800 },
        { id: "4", product: "Board B100", location: "PL-SA-01", created_date: "2024-02-16", onHand: 1800, inTransit: 600, safetyStock: 1600 },
        { id: "5", product: "System Rack", location: "DC-PA-03", created_date: "2024-02-18", onHand: 800, inTransit: 400, safetyStock: 1000 },
      ],
    },
  },
  {
    id: "logistics-shipments-table",
    headline: "Active Shipments and ETA",
    timestamp: "2024-12-04T11:15:00Z",
    preamble: "In-flight shipments with origin/destination and mode",
    content:
      "Track potential delays by lane and prioritize critical modes for expediting.",
    table: {
      rowIdentifier: "id",
      headers: [
        { text: "Shipment ID", accessorKey: "shipmentId" },
        { text: "Origin", accessorKey: "origin" },
        { text: "Destination", accessorKey: "destination" },
        { text: "Mode", accessorKey: "mode" },
        { text: "Created Date", accessorKey: "created_date" },
        { text: "ETA", accessorKey: "eta" },
        { text: "Status", accessorKey: "status" },
      ],
      rows: [
        { id: "1", shipmentId: "SHP-1001", origin: "LIM-02", destination: "BOG-01", mode: "Air", created_date: "2024-04-01", eta: "2024-04-03", status: "In-Transit" },
        { id: "2", shipmentId: "SHP-1002", origin: "AMS-01", destination: "FRA-02", mode: "Truck", created_date: "2024-04-02", eta: "2024-04-06", status: "Delayed" },
        { id: "3", shipmentId: "SHP-1003", origin: "SHA-01", destination: "LAX-01", mode: "Ocean", created_date: "2024-04-03", eta: "2024-04-25", status: "In-Transit" },
        { id: "4", shipmentId: "SHP-1004", origin: "MEX-01", destination: "DFW-01", mode: "Rail", created_date: "2024-04-04", eta: "2024-04-08", status: "Booked" },
      ],
    },
  },
  {
    id: "purchase-orders-table",
    headline: "Open Purchase Orders",
    timestamp: "2024-12-05T08:45:00Z",
    preamble: "POs with due dates and quantities",
    content:
      "Monitor overdue POs and aging to improve supplier execution.",
    table: {
      rowIdentifier: "id",
      headers: [
        { text: "PO Number", accessorKey: "poNumber" },
        { text: "Supplier", accessorKey: "supplier" },
        { text: "Created Date", accessorKey: "created_date" },
        { text: "Due Date", accessorKey: "dueDate" },
        { text: "Units", accessorKey: "units" },
        { text: "Status", accessorKey: "status" },
        { text: "Region", accessorKey: "region" },
      ],
      rows: [
        { id: "1", poNumber: "PO-7001", supplier: "Alpha Co", created_date: "2024-01-10", dueDate: "2024-02-05", units: 5000, status: "Open", region: "North America" },
        { id: "2", poNumber: "PO-7002", supplier: "Beta Ltd", created_date: "2024-01-15", dueDate: "2024-02-10", units: 3000, status: "Overdue", region: "Europe" },
        { id: "3", poNumber: "PO-7003", supplier: "Gamma Inc", created_date: "2024-01-20", dueDate: "2024-02-18", units: 4200, status: "Open", region: "Asia" },
        { id: "4", poNumber: "PO-7004", supplier: "Delta LLC", created_date: "2024-01-25", dueDate: "2024-02-20", units: 2700, status: "Closed", region: "Pacific" },
        { id: "5", poNumber: "PO-7005", supplier: "Epsilon BV", created_date: "2024-01-28", dueDate: "2024-02-25", units: 3800, status: "Open", region: "South America" },
      ],
    },
  },
  {
    id: "allocation-by-customer-table",
    headline: "Allocation by Customer",
    timestamp: "2024-12-06T13:20:00Z",
    preamble: "Requested vs Allocated units and fill rate",
    content:
      "Identify customers with low fill rate to take corrective action.",
    table: {
      rowIdentifier: "id",
      headers: [
        { text: "Customer", accessorKey: "customer" },
        { text: "Region", accessorKey: "region" },
        { text: "Created Date", accessorKey: "created_date" },
        { text: "Requested Units", accessorKey: "requested" },
        { text: "Allocated Units", accessorKey: "allocated" },
        { text: "Fill Rate %", accessorKey: "fillRate" },
      ],
      rows: [
        { id: "1", customer: "Customer A", region: "North America", created_date: "2024-05-01", requested: 12000, allocated: 9800, fillRate: 81.7 },
        { id: "2", customer: "Customer B", region: "Europe", created_date: "2024-05-02", requested: 8000, allocated: 7200, fillRate: 90.0 },
        { id: "3", customer: "Customer C", region: "Asia", created_date: "2024-05-03", requested: 15000, allocated: 11000, fillRate: 73.3 },
        { id: "4", customer: "Customer D", region: "Africa", created_date: "2024-05-04", requested: 6000, allocated: 5400, fillRate: 90.0 },
        { id: "5", customer: "Customer E", region: "South America", created_date: "2024-05-05", requested: 9500, allocated: 8000, fillRate: 84.2 },
      ],
    },
  },
];

module.exports = tableExamples;


